# Required software:
  # Latest PowerShell Core
  # git
    # Enable Git long paths so that files are cleaned correctly:
    # git config --system core.longpaths true
  # CodeQL (set in PATH)
  # EWDK with EWDK_ROOT set to the mounted EWDK path
# I also set the following in config.toml to shorten the build path:
  # builds_dir = "C:/a"

stages:
  - build

build-job:
  tags:
    - windows
    - ewdk
  stage: build
  parallel:
    matrix:
      - BUILD_ARCH:
          # x86 is no longer supported by new WDKs
          - x64
        BUILD_TYPE:
          - checked
          - free
  script:
    - Get-Content $Env:EWDK_ROOT\Version.txt
    - codeql.exe pack download codeql/cpp-queries@0.9.0 microsoft/windows-drivers@1.1.0
    - |
      Invoke-WebRequest `
        -Uri "https://raw.githubusercontent.com/microsoft/Windows-Driver-Developer-Supplemental-Tools/44a75acab6decc2676d0e0f045de47a20a238c3c/suites/windows_driver_recommended.qls" `
        -OutFile windows_driver_recommended.qls
    - |
      Set-Content -Path build.cmd -Value `
        "call %EWDK_ROOT%\BuildEnv\SetupBuildEnv.cmd",
        # CodeQL is incompatible with x86
        'pwsh.exe -NonInteractive -ExecutionPolicy Bypass -Command ".\build.ps1 -Type $Env:BUILD_TYPE -Arch $Env:BUILD_ARCH -CodeQL:($Env:BUILD_ARCH -ine ''x86'')"'
    - cmd.exe /c build.cmd
  artifacts:
    name: $CI_PROJECT_NAME
    paths:
      - $CI_PROJECT_NAME/
    when: on_success
    access: all
    expire_in: 30 days
